Vagrant.configure("2") do |config|
  config.vm.box = "ubuntubox"
  config.vm.network "public_network", ip: "192.168.1.100"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "M1.clone"
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install mysql-server
    #sudo mysql < 'C:/Users/Hakim SAGHIR/Desktop/linux/backups/users_db_save.sql'
    #sudo mysql users_db -e "SELECT * FROM user_tb"
  SHELL
end
